import { ArrowRight, Bot, Download, ShieldCheck, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import ProductCard from '../components/ProductCard';
import { marketplaceService } from '../service';
import type { Category, Product } from '../types';
export default function HomePage(){const[products,setProducts]=useState<Product[]>([]);const[cats,setCats]=useState<Category[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{Promise.all([marketplaceService.getProducts({featured:true,limit:8}),marketplaceService.getCategories()]).then(([p,c])=>{setProducts(p);setCats(c)}).finally(()=>setLoading(false))},[]);return <>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><Sparkles size={15}/> MARKETPLACE PRODUK DIGITAL #1</span><h1>AI That <em>Works</em><br/>For You.</h1><p>Temukan prompt, template, website, dan tools AI premium yang siap mempercepat pekerjaan dan pertumbuhan bisnis Anda.</p><div className="hero-actions"><Link className="btn primary" to="/products">Jelajahi Produk <ArrowRight size={18}/></Link><Link className="btn ghost" to="/about">Pelajari Lebih Lanjut</Link></div><div className="stats"><div><b>30+</b><span>Produk Premium</span></div><div><b>100%</b><span>Digital & Instan</span></div><div><b>24/7</b><span>Akses Produk</span></div></div></div><div className="hero-visual"><div className="orb"/><div className="showcase-card"><Bot size={48}/><span>AI PRODUCTIVITY PACK</span><h3>Kerja lebih cerdas, bukan lebih keras.</h3><div className="chips"><i>Prompt</i><i>Template</i><i>AI Tool</i></div></div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">KATEGORI</span><h2>Temukan solusi yang tepat</h2></div><Link to="/products">Lihat semua <ArrowRight size={16}/></Link></div><div className="category-grid">{cats.slice(0,8).map(c=><Link className="category-card" to={`/products?category=${c.category_id}`} key={String(c.category_id)}><span>{c.icon||'✦'}</span><h3>{c.name}</h3><p>Produk digital pilihan untuk kebutuhan Anda.</p></Link>)}</div></div></section>
<section className="section alt"><div className="container"><div className="section-head"><div><span className="eyebrow">PRODUK UNGGULAN</span><h2>Pilihan terbaik untuk Anda</h2></div><Link to="/products">Semua produk <ArrowRight size={16}/></Link></div>{loading?<div className="skeleton-grid">{[1,2,3,4].map(i=><div className="skeleton-card" key={i}/>)}</div>:products.length?<div className="product-grid">{products.map(p=><ProductCard product={p} key={p.id}/>)}</div>:<div className="empty">Belum ada produk unggulan.</div>}</div></section>
<section className="section"><div className="container"><div className="benefit-grid"><div><ShieldCheck/><h3>Transaksi Aman</h3><p>Pembayaran QRIS diverifikasi admin sebelum akses diberikan.</p></div><div><Download/><h3>Akses Digital</h3><p>Produk tersedia di halaman download setelah pembayaran disetujui.</p></div><div><Sparkles/><h3>Produk Kurasi</h3><p>Setiap produk dipilih untuk memberikan dampak nyata.</p></div></div></div></section>
<section className="cta"><div className="container"><span className="eyebrow">MULAI SEKARANG</span><h2>Tingkatkan produktivitas Anda bersama NAFI.</h2><Link className="btn primary" to="/register">Buat Akun Gratis <ArrowRight size={18}/></Link></div></section></>}
